* PG5200 Exam - Card Creator

**  Task
   Requirements [7/11]
   - [X] One text field for name (max 12 characters)
   - [X] drop down menu for +type+ move.
   - [X] An additional window where you can define a new +type+ move
     - Moves should have at least a name, max and min stats
       - move name
       - damage output - 0/180
         - ignore special cases for now
         # - what about '30+' or '30x'?
         # - if multiplicative: 10/50
       # - recoil?
       - energy cost
       # - secondary effect? status, heal, force opponent out?
       - description (with char limit.)
   - [X] at least three numerical stats inputs which limit input to numbers and limits max and min values based on something [3/3]
     - [X] hp 10/200, only products of 10 (round up?)
     - [X] level 1/100
     - [X] move damage
   - [X] a field that brings up a file selector to select an image for the card. it should verify that the file is an image, and the image should be displayed in the editor
   - [ ] the editor should have a button for storing the card to a database, empty all fields and be ready for the next card
   - [ ] the editor should have a browser that lets you look through existing cards and open them
   - [ ] it should be possible to delete cards from the database
   - [ ] multiple users should be able to add or update cards in parallel without the possibility of conflicts
   - [X] the editor should have the ability to export cards to JSON-files
   - [X] the editor should be able to import cards from JSON-files

     Notes:
      All numeric values (save for level) should be rounded to the nearest 10.


** Author
 Thomas Hartmann
