* PG5200 Exam - Card Creator

**  Task
   Requirements [1/11]
   - [X] One text field for name (max 12 characters)
   - [ ] drop down menu for +type+ move.
   - [ ] An additional window where you can define a new +type+ move
     - Moves should have at least a name, max and min stats
       - move name
       - damage output - 0/180
         - what about '30+' or '30x'?
         - if multiplicative: 10/50
       - recoil?
       - energy cost
       - secondary effect? status, heal, force opponent out?
       - description (with char limit.)
   - [ ] at least three numerical stats inputs which limit input to numbers and limits max and min values based on something [0/3]
     - [ ] hp 10/200, only products of 10 (round up?)
     - [ ] level 1/100
     - [ ] move damage
   - [ ] a field that brings up a file selector to select an image for the card. it should verify that the file is an image, and the image should be displayed in the editor
   - [ ] the editor should have a button for storing the card to a database, empty all fields and be ready for the next card
   - [ ] the editor should have a browser that lets you look through existing cards and open them
   - [ ] it should be possible to delete cards from the database
   - [ ] multiple users should be able to add or update cards in parallel without the possibility of conflicts
   - [ ] the editor should have the ability to export cards to JSON-files
   - [ ] the editor should be able to import cards from JSON-files

     Notes:
      All numeric values (save for level) should be rounded to the nearest 10.


** License
 All Pokémon names are owned by GameFreak and used within this project solely for educational means.

** Author
 Thomas Hartmann
